**Matrix Multiplication**
- tf.matmul() method
** Rules**
1. Inner dimension must match
    (m,n)@(n,p)
    for e.g
    (5,7)@(8,9) It will not work because n are different
    (5,8)@(8,9) It will work because n are same
  
2. The result matrix has the shape of outer dimension means:
    A (m,n)
    B (n,p)
    SO result has (m,p)
    e.g : (4,7)@(7,5) --> (4,5)

In [2]:
import tensorflow as tf
import numpy as np

In [8]:
tensor_A = tf.constant([[1,2],[3,4],[4,5]], dtype=tf.int32)
tensor_B = tf.constant([[5,6],[7,8]], dtype=tf.int32)
print('Shape of A',tensor_A.shape)
print('Shape of B',tensor_B.shape)

Shape of A (3, 2)
Shape of B (2, 2)


In [9]:
tensor_C = tf.matmul(tensor_A,tensor_B)
print(tensor_C)
print('Shape of tensor_C',tensor_C.shape)

tf.Tensor(
[[19 22]
 [43 50]
 [55 64]], shape=(3, 2), dtype=int32)
Shape of tensor_C (3, 2)


In [12]:
X = tf.constant([
    [1.,0.,-1.],
    [2.,3.,1.]
],dtype=tf.float32)
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  0., -1.],
       [ 2.,  3.,  1.]], dtype=float32)>

In [13]:
y = tf.constant([
    [4.],
    [5.],
    [6.]
], dtype=tf.float32)
y

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [14]:
print('X shape:',X.shape)
print('Y shape:',y.shape)

X shape: (2, 3)
Y shape: (3, 1)


In [15]:
Z = tf.matmul(X,y)
Z

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-2.],
       [29.]], dtype=float32)>

In [16]:
print(f'X-shape: {X.shape}, Y-shape: {y.shape}, Z-shape{Z.shape}')
print(X.numpy())
print(y.numpy())
print(Z.numpy())

X-shape: (2, 3), Y-shape: (3, 1), Z-shape(2, 1)
[[ 1.  0. -1.]
 [ 2.  3.  1.]]
[[4.]
 [5.]
 [6.]]
[[-2.]
 [29.]]


**Transpose:**

Transpose swaps axes. For 2D matrix shape (m,n) become (n,m) after transpose

In [21]:
tensor_one = tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]]
],dtype=tf.int32)
print(tensor_one)
print('\nShape of tensor one: ',tensor_one.shape)

tf.Tensor(
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)

Shape of tensor one:  (2, 2, 2)


In [22]:
tensor_one_transpose = tf.transpose(tensor_one)
print(tensor_one_transpose)
print('\nShape of tensor_one_transpose: ',tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)

Shape of tensor_one_transpose:  (2, 2, 2)


3D Transpose with explicit axis permutation

In [24]:
tensor_two = tf.constant([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
],dtype=tf.int32)
print(tensor_two)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [27]:
# swap first and last (0,1,2) --> (0,2,1)
tensor_two_transpose = tf.transpose(tensor_two,perm=[0,2,1])
print(tensor_two_transpose)
print('\nShape of tensor_two_transpose: ',tensor_two_transpose.shape)
print('\nShape of tensor_two: ',tensor_two.shape)

tf.Tensor(
[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]], shape=(2, 2, 2), dtype=int32)

Shape of tensor_two_transpose:  (2, 2, 2)

Shape of tensor_two:  (2, 2, 2)


**Reshape**

tf.reshape(tensor,new_shape)

Change the shape without change the data

In [33]:
tensor= tf.constant([
    [1,2,3],
    [4,5,6]
],dtype=tf.int32)
print(tensor)
print('Shape of tensor: ',tensor.shape)
print('Number of elements are: ',tf.size(tensor).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape of tensor:  (2, 3)
Number of elements are:  6


In [34]:
tensor_n1 = tf.reshape(tensor,shape=(3,2))
print(tensor_n1)
print('Shape of tensor: ',tensor_n1.shape)
print('Number of elements are: ',tf.size(tensor_n1).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor:  (3, 2)
Number of elements are:  6


In [35]:
tensor_n2 = tf.reshape(tensor,shape=(6,1))
print(tensor_n2)
print('Shape of tensor: ',tensor_n2.shape)
print('Number of elements are: ',tf.size(tensor_n2).numpy())

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)
Shape of tensor:  (6, 1)
Number of elements are:  6


In [36]:
tensor_n3 = tf.reshape(tensor,shape=(-1,2))
print(tensor_n3)
print('Shape of tensor: ',tensor_n3.shape)
print('Number of elements are: ',tf.size(tensor_n3).numpy())

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Shape of tensor:  (3, 2)
Number of elements are:  6


In [37]:
tensor_n2 = tf.reshape(tensor,shape=(-1,6))
print(tensor_n2)
print('Shape of tensor: ',tensor_n2.shape)
print('Number of elements are: ',tf.size(tensor_n2).numpy())

tf.Tensor([[1 2 3 4 5 6]], shape=(1, 6), dtype=int32)
Shape of tensor:  (1, 6)
Number of elements are:  6


Exercise

Reshape (2,6) --> (3,4) and (1,12)

In [38]:
tensor_given = tf.constant([[1, 2, 3, 4, 5, 6],
                 [7, 8, 9, 10, 11, 12]], dtype=tf.int32)

In [40]:
tensor_E1 = tf.reshape(tensor_given,shape=(3,4))
print(tensor_E1)
print('Shape of tensor: ',tensor_E1.shape)
print('Number of elements are: ',tf.size(tensor_E1).numpy())

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of tensor:  (3, 4)
Number of elements are:  12


In [41]:
tensor_E2 = tf.reshape(tensor_given,shape=(1,12))
print(tensor_E2)
print('Shape of tensor: ',tensor_E2.shape)
print('Number of elements are: ',tf.size(tensor_E2).numpy())

tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)
Shape of tensor:  (1, 12)
Number of elements are:  12
