In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


In [4]:
#Create Tensor with constant
# Function that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [5]:
scalar.ndim

0

In [6]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
second_matrix=tf.constant([[5,7],
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [11]:
second_matrix.ndim

2

In [14]:
third_matrix=tf.constant(
    [[
    [5,7,8],
    [3,8,9],
    [3,9,4],
    [4,2,5],
    [8,6,8]
    ]]
    )
third_matrix

<tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[5, 7, 8],
        [3, 8, 9],
        [3, 9, 4],
        [4, 2, 5],
        [8, 6, 8]]], dtype=int32)>

In [15]:
third_matrix.ndim

3

In [16]:
second_matrix=tf.constant([[5,7,7],
                           [3,8,8],
                           [3,9,9],
                           [4,2,4],
                           [8,6,6]],dtype=tf.float16)
second_matrix

<tf.Tensor: shape=(5, 3), dtype=float16, numpy=
array([[5., 7., 7.],
       [3., 8., 8.],
       [3., 9., 9.],
       [4., 2., 4.],
       [8., 6., 6.]], dtype=float16)>

In [17]:
# Tensor: an n-dimensional array of numbers (n=0,n=1,n=2,..)
tensor=tf.constant([[[1,2],[3,4],[5,6],[7,8],[9,10]]])
tensor

<tf.Tensor: shape=(1, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]], dtype=int32)>

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

TensorShape([1, 5, 2])

In [22]:
print('Scalar Information')
print('Shape: ',scalar.shape)
print('Dimension: ',scalar.ndim)
print('Rank: ',tf.rank(scalar).numpy())
print('Size: ',tf.size(scalar))

Scalar Information
Shape:  ()
Dimension:  0
Rank:  0
Size:  tf.Tensor(1, shape=(), dtype=int32)


In [23]:
print('Vector Information')
print('Shape: ',vector.shape)
print('Dimension: ',vector.ndim)
print('Rank: ',tf.rank(vector).numpy())
print('Size: ',tf.size(vector))

Vector Information
Shape:  (2,)
Dimension:  1
Rank:  1
Size:  tf.Tensor(2, shape=(), dtype=int32)


In [24]:
print('Matrix Information')
print('Shape: ',matrix.shape)
print('Dimension: ',matrix.ndim)
print('Rank: ',tf.rank(matrix).numpy())
print('Size: ',tf.size(matrix))

Matrix Information
Shape:  (2, 2)
Dimension:  2
Rank:  2
Size:  tf.Tensor(4, shape=(), dtype=int32)


In [25]:
print('Tensor Information')
print('Shape: ',tensor.shape)
print('Dimension: ',tensor.ndim)
print('Rank: ',tf.rank(tensor).numpy())
print('Size: ',tf.size(tensor))

Tensor Information
Shape:  (1, 5, 2)
Dimension:  3
Rank:  3
Size:  tf.Tensor(10, shape=(), dtype=int32)


In [28]:
# Creating Tensor using variables
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [29]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [30]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [31]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [33]:
# unchangeable_tensor[0].assign(12)
# unchangeable_tensor
# This will be error because it cant change constant tensor. It is immutable. Unchangeable

In [35]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [38]:
random_tensor_2 = tf.random.uniform(shape=(300,120),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 120), dtype=float32, numpy=
array([[0.39534044, 0.05475879, 0.44676328, ..., 0.41209984, 0.9783181 ,
        0.73293495],
       [0.3719746 , 0.47014523, 0.2128048 , ..., 0.09185362, 0.1606121 ,
        0.14779627],
       [0.5441781 , 0.06632197, 0.40330136, ..., 0.17995465, 0.21624863,
        0.29977918],
       ...,
       [0.1604594 , 0.30180657, 0.9794409 , ..., 0.12399304, 0.7737076 ,
        0.3994354 ],
       [0.64411604, 0.5385188 , 0.31884122, ..., 0.90001833, 0.5647974 ,
        0.57045496],
       [0.40998197, 0.23347569, 0.9546577 , ..., 0.0596987 , 0.48100126,
        0.3156377 ]], dtype=float32)>

In [41]:
random_tensor_3 = tf.random.Generator.from_seed(42)
random_tensor_3 = random_tensor_3.normal(shape=(3,2))
random_tensor_4 = tf.random.Generator.from_seed(15)
random_tensor_4 = random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.33149973, -0.5445254 ],
        [ 1.5222508 ,  0.59303206],
        [-0.63509274,  0.3703566 ]], dtype=float32)>)

In [44]:
# Creating tensors using zeros
tensor_zeros = tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [45]:
tensor_zeros = tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [48]:
import numpy as np
numpy_array = np.arange(1,25,dtype=np.int16)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [49]:
numpy_tensor = tf.constant(numpy_tensor,shape=(2,3,4))
numpy_tensor

NameError: name 'numpy_tensor' is not defined

**Arthmetic Operations with tensors**
- Add
- Sub
- Multinomial
- Div

In [54]:
tensor_one = tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [55]:
# tensor_one+15
tf.add(tensor_one,15) # second way

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [56]:
# tensor_one-4
tf.subtract(tensor_one,4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  5],
       [-2,  1]], dtype=int32)>

In [57]:
# tensor_one*3
tf.multiply(tensor_one,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 27],
       [ 6, 15]], dtype=int32)>

In [58]:
# tensor_one/3
tf.divide(tensor_one,3)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.66666667, 3.        ],
       [0.66666667, 1.66666667]])>

In [61]:
tensor_new = tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [62]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 3), dtype=float16, numpy=
array([[2.236, 2.646, 2.646],
       [1.732, 2.828, 2.828],
       [1.732, 3.   , 3.   ],
       [2.   , 1.414, 2.   ],
       [2.828, 2.45 , 2.45 ]], dtype=float16)>

**Exercise**
Create two tensors with random values between 0 and 1, shape is [6,300]
- Number of elements
- Size,
- Rank,
- Shape

In [67]:
import numpy as np

# Two tensors with random values between 0 and 1
tensor1 = np.random.rand(6, 300)
tensor2 = np.random.rand(6, 300)


In [64]:
print("Tensor 1:")
print("Shape:", tensor1.shape)
print("Number of elements:", tensor1.size)
print("Rank (number of dimensions):", tensor1.ndim)
print("Data type:", tensor1.dtype)

print("\nTensor 2:")
print("Shape:", tensor2.shape)
print("Number of elements:", tensor2.size)
print("Rank (number of dimensions):", tensor2.ndim)
print("Data type:", tensor2.dtype)


Tensor 1:
Shape: (6, 300)
Number of elements: 1800
Rank (number of dimensions): 2
Data type: float64

Tensor 2:
Shape: (6, 300)
Number of elements: 1800
Rank (number of dimensions): 2
Data type: float64
