# Mathematical Operation

In [2]:
import numpy as np

In [3]:
array1=np.array([10,20,30,40,50])

In [4]:
total=np.sum(array1)

In [5]:
print(total)

150


In [8]:
print('Mean: ',np.mean(array1))

Mean:  30.0


In [9]:
print('Min: ',np.min(array1))

Min:  10


In [10]:
print('Max: ',np.max(array1))

Max:  50


In [11]:
print('Index of Min: ',np.argmin(array1))

Index of Min:  0


In [13]:
print('Index of Max: ',np.argmax(array1))

Index of Max:  4


In [16]:
my_array=np.array([100,200,300,400,500,700,800,450])

In [17]:
print(my_array)

[100 200 300 400 500 700 800 450]


# Searching and sorting example in 1 D array

In [18]:
sorted_array=np.sort(my_array)

In [21]:
print('**Sorted Array**')
print(sorted_array)

**Sorted Array**
[100 200 300 400 450 500 700 800]


In [23]:
print('Is there any item greater tha 400?: ',np.any(sorted_array>400))

Is there any item greater tha 400?:  True


In [24]:
print('All greater than 500?: ',np.all(sorted_array>500))

All greater than 500?:  False


In [26]:
print('Where values >400',np.where(sorted_array>400))

Where values >400 (array([4, 5, 6, 7]),)


In [27]:
print('All number than 500')
for num in np.where(sorted_array>500):
    print(num)

All number than 500
[6 7]


In [30]:
print('All number than 500')
for num in sorted_array>500:
    print(num)

All number than 500
False
False
False
False
False
False
True
True


In [33]:
selected_values=sorted_array[sorted_array>500]

In [34]:
print(selected_values)

[700 800]


In [35]:
print('All number than 500')
for num in selected_values:
    print(num)

All number than 500
700
800


In [36]:
print(' ',sorted_array[sorted_array>500])

  [700 800]


# Slicing 1 D Array
    ## To take elements from starting to end of index
    ## e.g. [start:end]

In [44]:
print(my_array)

[100 200 300 400 500 700 800 450]


In [49]:
slice_my_array=my_array[1:4]
print(slice_my_array)

[200 300 400]


# Starting from an index and going till last

In [40]:
print(my_array)

[100 200 300 400 500 700 800 450]


In [43]:
print(my_array[3:])

[400 500 700 800 450]


# Step
    ## [Start:end:step]
    ## Step: every step element

In [50]:
our_slice=sorted_array[1:6:2]
print(our_slice)

[200 400 500]


In [51]:
print('Original Array')
print(sorted_array)

Original Array
[100 200 300 400 450 500 700 800]


In [53]:
print('Every Third Element')
every_third_element=sorted_array[::3]
print(every_third_element)

Every Third Element
[100 400 700]


# Slice Reverse

In [54]:
print('Original Array')
print(sorted_array)
print('Reverse Array: ',sorted_array[::-1])

Original Array
[100 200 300 400 450 500 700 800]
Reverse Array:  [800 700 500 450 400 300 200 100]


In [58]:
print('Last five elements:')
print(sorted_array[-5::])

Last five elements:
[400 450 500 700 800]


In [60]:
print('Slicing Done')

Slicing Done
