In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

     Name  Age  Marks
0    John   20     85
1   Alice   22     90
2     Bob   21     78
3    Sara   23     92
4  Qaiyim   26     90
5   Intan   25     89


In [3]:
marks=df['Marks'].to_numpy()

In [4]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 89]


In [5]:
print('Highest Marks: ',np.max(marks))

Highest Marks:  92


In [6]:
print('Lowest Marks: ',np.min(marks))

Lowest Marks:  78


In [7]:
print('Average Marks: ',np.mean(marks))

Average Marks:  87.33333333333333


# .loc: Label Based
# .iloc: Index Based

In [8]:
print(df)

     Name  Age  Marks
0    John   20     85
1   Alice   22     90
2     Bob   21     78
3    Sara   23     92
4  Qaiyim   26     90
5   Intan   25     89


In [14]:
print(df.loc[2,['Name','Marks']])

Name     Bob
Marks     78
Name: 2, dtype: object


In [18]:
print(df.iloc[4,[0,2]])

Name     Qaiyim
Marks        90
Name: 4, dtype: object


# Axis in Numpy:
    ## Axis 0: vertical direction: works column wise
    ## AXis 1: horizontal direction: works rows wise

# We have two students marks in 3 subjects
    # [45,65,78],[67,89,90]

In [24]:
marks_array=np.array([[7,4,9],[3,6,9]])

In [25]:
print(marks_array)

[[7 4 9]
 [3 6 9]]


In [26]:
print('Sum down eaxh column',np.sum(marks_array,axis=0))

Sum down eaxh column [10 10 18]


In [27]:
print('Sum down eaxh row',np.sum(marks_array,axis=1))

Sum down eaxh row [20 18]


In [28]:
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 89]


In [29]:
print(df)

     Name  Age  Marks
0    John   20     85
1   Alice   22     90
2     Bob   21     78
3    Sara   23     92
4  Qaiyim   26     90
5   Intan   25     89


# Find the student Name who got highest marks

In [31]:
highest=df.loc[df['Marks'].idxmax(),'Name']
print(highest)

Sara


In [32]:
lowest=df.loc[df['Marks'].idxmin(),'Name']
print(lowest)

Bob


In [33]:
print('Next Example')

Next Example


In [37]:
top_index=df['Marks'].idxmax()
top_students=df.iloc[top_index,df.columns.get_loc('Name')]
print('Highest in the class is ',top_students)

Highest in the class is  Sara
